env:
  browser: true
  es6: true
  node: true
extends:
  - 'airbnb'
  - 'prettier'
overrides:
  - files: ./src/**/*spec.ts
    rules:
      '@typescript-eslint/no-magic-numbers': 'off'
parserOptions:
  ecmaVersion: 10
  project: tsconfig.json
  sourceType: module
rules:
  prettier/prettier: 'error',
  no-new: 'off',
  global-require: 'off',
  no-shadow: 'off'
